### ISSUE TITLE
addUnique and remove

### ISSUE THREAD

**Issue by d-reinhold** [pivotal-cf/pui-cursor#2]
How about adding `addUnique` and `remove` to the cursor API?

```
function addUnique($cursor, scalar) {
  $cursor.apply(vector => {
    if (!vector.includes(scalar)) vector.push(scalar);
    return vector;
  });
}

function remove($cursor, scalar) {
  $cursor.apply(vector => {
    return vector.filter(s => s !== scalar);
  });
}
```

**Comment by rdy** [comment]
We already have remove which does what you want now, I'm not 100% sold on the add unique since it could only ever work if the object matches exactly or you could specify some key. That sort of makes addUnique a lot less useful.
